local_backend: true
slug:
  encoding: "unicode"
  clean_accents: false
  sanitize_replacement: "-"

backend:
  name: github
  repo: ironkingironking/verafides-site
  branch: main
  base_url: https://verafides.ch
  auth_endpoint: api/cms/auth
  auth_scope: repo

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Aktuelles"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Entwurf", name: "draft", widget: "boolean", default: false, required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Seiten"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Titel", name: "title", widget: "string", required: false }
      - { label: "URL", name: "url", widget: "string", required: false }
      - { label: "Slug", name: "slug", widget: "string", required: false }
      - { label: "Typ", name: "type", widget: "string", required: false }
      - { label: "Formular", name: "form", widget: "string", required: false }
      - { label: "Kontaktformular", name: "contact_form", widget: "boolean", default: false, required: false }
      - { label: "Dokumentliste", name: "documents_list", widget: "boolean", default: false, required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }

  - name: "page_indexes"
    label: "Seiten-Übersichten"
    editor:
      preview: false
    files:
      - label: "Startseite"
        name: "root"
        file: "content/_index.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown", required: false }

      - label: "Aktuelles-Übersicht"
        name: "aktuelles_index"
        file: "content/posts/_index.md"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "URL", name: "url", widget: "string", required: false }

      - label: "Dokumente-Übersicht"
        name: "documents_index"
        file: "content/documents/_index.md"
        fields:
          - { label: "Titel", name: "title", widget: "string" }

      - label: "Veranstaltungen-Übersicht"
        name: "events_index"
        file: "content/events/_index.md"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "URL", name: "url", widget: "string", required: false }
